language: python
sudo: required

env:
  global:
    - _VERSION=1.0

  matrix:
    - LUA="lua=5.3"
    - LUA="lua=5.2"
    - LUA="lua=5.1"
    - LUA="luajit=2.1"
    - LUA="luajit=2.0"

before_install:
  # Put back the links for libyaml, which are missing on recent Travis VMs
  - test -f /usr/lib/libyaml.so ||
    sudo find /usr/lib -name 'libyaml*' -exec ln -s {} /usr/lib \;

  - pip install hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PWD/here/bin:$PATH

  - luarocks install ansicolors
  - luarocks install specl
  - luarocks install --server=http://rocks.moonscript.org/manifests/gvvaughan ldoc

install:
  - make
  - luarocks make

script:
  - make check

notifications:
  slack: aspirinc:JyWeNrIdS0J5nf2Pn2BS1cih
